[data]
file = "data/banana_quality.csv"
inputStart = 0
inputSize = 7
outputStart = 7
outputSize = 1
seed = 42
testShare = 0.2

[network]
seed = 42
weightInitializer = "GLOROT_UNIFORM"

# 300 - 300 - 0.03 LR geht auch gut
[[network.layer]]
neurons = 50
activationFunction = "SWISH"

[[network.layer]]
neurons = 50
activationFunction = "SWISH"

[[network.layer]]
neurons = 1
activationFunction = "SIGMOID"

[trainer]
lossFunction = "CROSS_ENTROPY_LOSS"
maxEpochs = 30
shuffleEpoch = true
batchSize = 10
learningRate = 0.03
#exportFile = "models/test.knn"

[trainer.earlyStopping]
minDelta = 0.002
patience = 5

[scorer]
lossFunction = "CROSS_ENTROPY_LOSS"
type = "ClassificationScorer"

[visualization]
enabled = true

[visualization.heatmap]
interval = 10
colorScheme = "GREEN_RED"
[visualization.sankey]
interval = 10
