[data]
file = "data/banana_quality.csv"
inputStart = 0
inputSize = 7
outputStart = 7
outputSize = 1
seed = 42
testShare = 0.2

[network]
seed = 42
weightInitializer = "GLOROT_UNIFORM"

# 300 - 300 - 0.03 LR geht auch gut
[[network.layer]]
neurons = 50
activationFunction = "SWISH"

[[network.layer]]
neurons = 50
activationFunction = "SWISH"

[[network.layer]]
neurons = 1
activationFunction = "SIGMOID"

[trainer]
lossFunction = "CROSS_ENTROPY_LOSS"
maxEpochs = 20
shuffleEpoch = true
batchSize = 1
learningRate = 0.04
visualization = false
#exportFile = "models/test.knn"

[scorer]
lossFunction = "CROSS_ENTROPY_LOSS"
type = "ClassificationScorer"

[visualization]
heatmapInterval = 10
sankeyInterval = 10