[data]
file = "data/banana_quality.csv"
inputStart = 0
inputSize = 7
outputStart = 7
outputSize = 1
seed = 42
testShare = 0.2

[network]
seed = 42
weightInitializer = "GLOROT_UNIFORM"

[[network.layer]]
neurons = 100
activationFunction = "RELU"

[[network.layer]]
neurons = 100
activationFunction = "RELU"

[[network.layer]]
neurons = 1
activationFunction = "SIGMOID"

[trainer]
lossFunction = "CROSS_ENTROPY_LOSS"
maxEpochs = 100
shuffleEpoch = true
batchSize = 32
learningRate = 0.04
logLoss = false

[scorer]
lossFunction = "CROSS_ENTROPY_LOSS"
type = "ClassificationScorer"
