[data]
file = "data/banana_quality.csv"
inputStart = 0
inputSize = 7
outputStart = 7
outputSize = 1
seed = 42
testShare = 0.2

[network]
importFile = "models/bq.knn"

[visualization.heatmap]
interval = 1
[visualization.sankey]
interval = 1

[scorer]
type = "ClassificationScorer"